#ifndef DIALECT_Vtc_VtcOPS_H
#define DIALECT_Vtc_VtcOPS_H

// #include "Dialect/Vtc/VtcTypes.h"
// #include "Dialect/Vtc/VtcUtils.h"
#include "mlir/IR/Attributes.h"
#include "mlir/IR/BuiltinOps.h"
#include "mlir/IR/MLIRContext.h"
#include "mlir/IR/PatternMatch.h"
#include "mlir/Interfaces/SideEffectInterfaces.h"
#include "mlir/Support/LogicalResult.h"
#include <cstdint>
#include <numeric>

namespace mlir {
namespace Vtc {
#include "Dialect/Vtc/ShapeInterface.h.inc"
} // namespace Vtc
} // namespace mlir

/// Retrieve the class declarations generated by TableGen
#define GET_OP_CLASSES
#include "Dialect/Vtc/VtcOps.h.inc"

namespace mlir {
namespace vtc {


} // namespace Vtc
} // namespace mlir

#endif // DIALECT_Vtc_VtcOPS_H
